// DI BERIKAN ARRAYS OF OF MENU MAKANAN
// DI BERIKAN LIST OF BAHAN BAKU

// HARGA JUAL YANG DISEBUTKAN BELUM TERMASUK PPN 10% DAN BIAYA LAYANAN 4%
// HARGA BAHAN BAKU ADALAH, HARGA YANG DIKELUARKAN RESTO UNTUK MODAL AWAL BAHAN BAKU
// HARGA JUAL ADALAH HARGA JUAL MASING2 MENU
// HARGA NETT ADALAH HARGA JUAL YANG HARUS DIBAYAR CUSTOMER, TERMASUK HARGA_JUAL + PPN + LAYANAN
// JUMLAH KEUNTUNGAN ADALAH DEVIDEN ANTARA HARGA_NETT DAN HARGA BAHAN BAKU

// BUATLAH OUTPUT SEPERTI CONTOH DIBAWAH
// BONUS CHALLANGE (URUTKAN BERDASARKAN KEUNTUNGAN TERBESAR - KE TERKECIL)
// || NAMA MENU || HARGA_BAHAN_BAKU || HARGA_JUAL || HARGA_NETT || JUMLAH_PESANANAN || JUMLAH_KEUNTUNGAN