// DI BERIKAN ARRAYS OF OF MENU MAKANAN
// DI BERIKAN LIST OF BAHAN BAKU

// HARGA JUAL YANG DISEBUTKAN BELUM TERMASUK PPN 10% DAN BIAYA LAYANAN 4%

// BUATLAH OUTPUT SEPERTI CONTOH DIBAWAH
// || NAMA MENU || HARGA_BAHAN_BAKU || HARGA_JUAL || HARGA_NETT || JUMLAH_PESANANAN || JUMLAH_KEUNTUNGAN